class "Marco Rossi"
class "Tarma Roving"
class "Eri Kasamoto"
class "Fio Germi"
class "Clark Still"
class "Ralf Jones"
class "Trevor Spacey"
class "Nadia Cassel"
class "Leona Heiden"
class "Walter Rian"
class "Soldado Rebelde"
class "Momias"
class "Pistola"
class "ametralladora"
class "Granada"
class "Tanque"
class "jeep"
class "Helicoptero"
class "Vida"
class "Escopeta"
class "Lanzallamas"
class "Cuchillo"
class "Camel Slug"
class "slug Mariner"
class "Prisionero de Guerra"
class "General Modern"
class "Allen O'Neil"
class "Caja de Suministros"
class "Puntaje"
class "Comida"
"Marco Rossi" *--> "Vida"
"Tarma Roving" *--> "Vida"
"Eri Kasamoto" *--> "Vida"
"Fio Germi" *--> "Vida"
"Soldado Rebelde" *--> "Vida"
"Marco Rossi" *--> "Puntaje"
"Marco Rossi" o--> "Pistola"
"Tarma Roving" o--> "Escopeta"
"Eri Kasamoto" o--> "Granada"
"Fio Germi" o--> "ametralladora"
"Trevor Spacey" o--> "Cuchillo"
"Nadia Cassel" o--> "Lanzallamas"
"Marco Rossi" o--> "Tanque"
"Tarma Roving" o--> "jeep"
"Eri Kasamoto" o--> "Helicoptero"
"Fio Germi" o--> "Camel Slug"
"Leona Heiden" o--> "slug Mariner"
"Walter Rian" o--> "Caja de Suministros"
"Prisionero de Guerra" o--> "Comida"
"General Modern" o--> "Helicoptero"
"Allen O'Neil" o--> "ametralladora"
"Momias" o--> "Granada"
"Ralf Jones" o--> "Pistola"
"Clark Still" o--> "Pistola"
"Soldado Rebelde" o--> "jeep"